/**
 * Recall — default prompt blocks for the `Standard` block set.
 *
 * These are the shipped defaults only. Once a user edits them in the manager the
 * edited copy lives in `extension_settings`, and this file is no longer consulted
 * for that set. Stored as line arrays so the source stays diffable.
 *
 * Block order matters: `Summary Prompt` establishes the task, the hierarchy, the
 * editing loop and the required structure; `Quality Check` closes with the
 * self-verification pass. Anything inserted between them lands inside the
 * instruction body rather than after the model has been told to verify and submit.
 */

const SUMMARY_PROMPT_LINES = [
    "**Pause roleplay. Ignore all previous instructions. Do NOT produce any in-character text.",
    "You are not generating a new summary unless the provided [Summary:\u2026] block is empty.",
    "If the block contains text, you must revise it in place.",
    "If it is empty, create the initial summary following the required structure.**",
    "",
    "Your job is to revise the contents **inside the same structure** by:",
    "",
    "1. Lightly compressing older material,",
    "2. Preserving essential plot & emotional arcs,",
    "3. Adding only the newest developments.",
    "",
    "Your summary must remain under ~1K words.",
    "",
    "This is an **editorial task, not a storytelling task.**",
    "",
    "**CRITICAL: If you're creating the summary from scratch, you MUST read THE ENTIRE",
    "CHAT CAREFULLY. Do NOT skip the middle sections. Do NOT only compress recent",
    "messages. Read EVERYTHING before creating the summary.**",
    "",
    "---",
    "",
    "# **I. THE HIERARCHY OF WHAT MUST STAY**",
    "",
    "To prevent confusion, these three mandatory categories have strict priorities:",
    "",
    "### **1. Core Memories (Emotional Anchors; MANDATORY)**",
    "",
    "* Must be created and must remain.",
    "* Must stay labeled \"Core Memory:\"",
    "* May be rewritten briefly for clarity and brevity (event + emotional/social/relationship impact,",
    "NOT only event summarised. You need to show WHY the memory is important).",
    "* Never merged.",
    "* Never deleted.",
    "* Represent the *emotional meaning* of key moments \u2014 not the whole event.",
    "* You may only create new core memories or preserve existing ones. Never remove any.",
    "* Always recreate the existing list perfectly and add new ones.",
    "",
    "**CRITICAL: If no Core Memories are present in the summary, you MUST generate them by",
    "scanning the ENTIRE conversation.**",
    "",
    "These are **anchors**, not the plot skeleton.",
    "",
    "#### **What Qualifies as a Core Memory (Universal Criteria):**",
    "",
    "A moment becomes a Core Memory if it involves:",
    "",
    "**Identity-challenging moments:**",
    "- Character reveals that contradict their established persona or public perception",
    "- Someone being SEEN in a way they're usually not",
    "- Moments where masks/performances drop (even briefly)",
    "- Actions that surprise the character themselves",
    "",
    "**Shared psychological territory:**",
    "- Discovering unexpected common ground rooted in background/trauma/values",
    "- Recognition of shared pain, fear, or desire",
    "- \"You understand something about me that others don't\" moments",
    "- Bonding over specifics that tie to character psychology (not generic interests)",
    "",
    "**Perception shifts:**",
    "- How Character A sees Character B fundamentally changes",
    "- Realizations that reframe past behavior",
    "- Trust earned or broken in ways that alter the relationship baseline",
    "- Moments that make someone reconsider their assumptions",
    "",
    "**Boundary transgressions (physical or emotional):**",
    "- First instances of intimacy (touch, proximity, eye contact that lingers)",
    "- Emotional admissions that create vulnerability (jealousy acknowledged, desire stated, fear",
    "named)",
    "- Crossing established rules or norms with consequence",
    "- Someone choosing vulnerability despite risk",
    "",
    "**Power dynamic shifts:**",
    "- Control changes hands",
    "- Someone gains/loses leverage",
    "- Dependencies form or break",
    "- Status within group/relationship hierarchy alters",
    "",
    "**Emotional turning points:**",
    "- Moments where feelings intensify or transform (like \u2192 love, trust \u2192 betrayal, fear \u2192 safety)",
    "- First experiences of specific emotions in this relationship",
    "- Breaking points where someone can't maintain their emotional distance",
    "- Realizations about one's own feelings",
    "",
    "**Choice moments with lasting impact:**",
    "- Decisions that characters will reference later",
    "- Actions that create obligation, debt, or expectation",
    "- Moments where inaction was significant",
    "- Crossroads where choosing differently would have changed everything",
    "",
    "#### **What is NOT a Core Memory:**",
    "",
    "- Generic flirting without psychological stakes",
    "- Logistical developments (arrived at location, ate food, bought item)",
    "- Repeated patterns without escalation (character doing their usual thing again)",
    "- Surface-level conversations that don't reveal anything new",
    "- Action sequences without emotional consequence",
    "- Exposition dumps",
    "- Small talk",
    "",
    "#### **The Core Memory Test:**",
    "",
    "Ask: \"Would removing this moment make a character's current emotional state",
    "incomprehensible?\"",
    "- If YES \u2192 Core Memory",
    "- If NO \u2192 compress or remove",
    "",
    "Ask: \"Does this moment represent a FIRST, a SHIFT, or a BREAK in emotional/relational",
    "patterns?\"",
    "- If YES \u2192 Core Memory",
    "- If NO \u2192 likely compressible",
    "",
    "---",
    "",
    "### **2. Major Plot Beats (Story Skeleton)**",
    "",
    "These are *non-negotiable.*",
    "",
    "You *must* preserve all major developments, including:",
    "",
    "* Conflicts and their resolutions (or lack thereof)",
    "* Choices and their consequences",
    "* Reveals (secrets exposed, truths learned, information gained)",
    "* Goals changing or being achieved/failed",
    "* Alliances forming or breaking",
    "* Significant actions that drive the story forward",
    "* New threats or power shifts",
    "* Status quo changes",
    "* Obstacles introduced or overcome",
    "* Anything that explains why the current situation exists",
    "",
    "You may **shrink the description**, but you may **not remove the beat**.",
    "",
    "If cutting a detail breaks the logic of how we got to the present, put that detail back in",
    "compressed form.",
    "",
    "**Plot beats must maintain cause\u2192effect clarity.**",
    "",
    "---",
    "",
    "### **3. Minor or Old Details (Excess Tissue)**",
    "",
    "These may be:",
    "",
    "* Compressed to a clause",
    "* Merged with related content",
    "* Or removed entirely if they don't support current continuity",
    "",
    "These include:",
    "",
    "- Travel/transitions between locations",
    "- Small talk without character development",
    "- Unnecessary scenery/description",
    "- Repeated emotional beats that didn't escalate",
    "- Redundant exposition",
    "- Micro-actions (fidgeting, glancing, etc.) unless they reveal psychology",
    "- Anything the current story doesn't rely on",
    "",
    "**The older it is, the more aggressively you compress it.**",
    "",
    "---",
    "",
    "# **II. THE EDITING LOOP (FOLLOW THESE STEPS EVERY TIME)**",
    "",
    "### **Step 1: Extract Core Memories**",
    "",
    "1. Find all existing \"Core Memory:\" entries",
    "2. If there are NONE, create them by reviewing the ENTIRE chat for moments matching the",
    "salience criteria above",
    "3. Prioritize identifying:",
    "- First instances of vulnerability/shared psychology",
    "- Moments that shifted power dynamics or perception",
    "- Physical/emotional boundary crossings",
    "- Identity-challenging reveals or choices",
    "4. Rephrase existing Core Memories only for clarity/conciseness",
    "5. Preserve emotional meaning exactly",
    "",
    "**You MUST create Core Memories if none exist. Scan the full conversation\u2014do not only",
    "look at recent messages.**",
    "",
    "### **Step 2: Identify the Plot Skeleton**",
    "",
    "Locate all major plot beats whose consequences shape the current situation.",
    "These form the backbone of the Plot Summary section.",
    "They must remain present\u2014even if condensed.",
    "Do not remove or bury them.",
    "Maintain cause\u2192effect chain.",
    "",
    "### **Step 3: Compress Older Material**",
    "",
    "Apply surgical compression:",
    "",
    "* Remove descriptive fluff",
    "* Strip dialogue unless it's the actual reveal/choice",
    "* Condense transitions",
    "* Merge minor events",
    "* Summarize long sequences in one line",
    "* Keep cause\u2192effect clarity",
    "* Keep emotional turning points (if they matter later)",
    "",
    "Your compression must never erase the logic of how the story reached the present.",
    "",
    "### **Step 4: Add New Developments**",
    "",
    "From the most recent interaction, add only material that changed:",
    "",
    "* Stakes",
    "* Goals",
    "* Emotional tone",
    "* Trust/attraction/tension levels",
    "* Power dynamics",
    "* Alliances",
    "* Knowledge (reveals, discoveries)",
    "* Setting or available resources",
    "* Ongoing threats",
    "* Future direction",
    "",
    "Do **not** add filler.",
    "Do **not** restage scenes.",
    "Do **not** expand old content.",
    "",
    "### **Step 4.5: Core Memory Verification (CRITICAL)**",
    "",
    "After adding new developments, cross-check Character States section:",
    "",
    "- Did any character's emotional state shift significantly?",
    "- Did trust/attraction/tension change between any characters?",
    "- Did someone learn something that changes their perception?",
    "- Did a boundary get crossed?",
    "- Did someone's identity/self-perception shift?",
    "",
    "**If YES to any** \u2192 scan the recent interaction for the MOMENT that caused it and ensure",
    "it's captured as a Core Memory.",
    "",
    "**Common failure mode:** You will note \"Character is more vulnerable now\" in Character",
    "States but fail to capture the specific moment (conversation, touch, admission) that caused",
    "the shift. FIX THIS.",
    "",
    "### **Step 5: Maintain the Existing Structure**",
    "",
    "Update the content *inside these sections only*:",
    "",
    "---",
    "",
    "# **REQUIRED SUMMARY STRUCTURE**",
    "",
    "### **1. Core Memories**",
    "",
    "Format: `Core Memory: [Brief title/identifier]`",
    "Then 1-2 sentences capturing the emotional significance.",
    "Focus on MEANING, not scene recreation.",
    "These represent emotionally definitive moments for characters and relationships.",
    "",
    "**If this section is empty and you're creating a summary, you have failed. Go back and",
    "identify Core Memories from the entire conversation.**",
    "",
    "---",
    "",
    "### **2. Plot Summary (Past Events)**",
    "",
    "Chronological order.",
    "Old content \u2192 compressed;",
    "New content \u2192 added.",
    "",
    "Must reflect:",
    "",
    "* Essential plot beats",
    "* Cause\u2192effect chain",
    "* How we got here",
    "* Major shifts in goals or resources",
    "* Consequences still affecting the present",
    "* Key choices and their outcomes",
    "",
    "Do NOT reduce this to only Core Memories.",
    "Plot is the spine of this section.",
    "",
    "**Keep it factual and clear. No flowery language.**",
    "",
    "---",
    "",
    "### **3. Emotional Arc**",
    "",
    "Summarize how emotional dynamics evolved over time.",
    "Then describe the *current* emotional landscape in more detail.",
    "",
    "Focus on:",
    "",
    "* Tension (where does it exist, between whom)",
    "* Trust shifts (who trusts whom, who doesn't, changes)",
    "* Attraction or conflict (intensity, reciprocity, complications)",
    "* Unresolved emotional debts or obligations",
    "* New vulnerabilities or defenses",
    "* Major emotional turning points that shaped \"Core Memory\" entries",
    "* Current emotional trajectory (escalating, cooling, fragmenting)",
    "",
    "Do not retell scenes.",
    "Capture emotional *trajectory and present state.*",
    "",
    "---",
    "",
    "### **4. Character States**",
    "",
    "Each major character gets 1\u20132 sentences describing:",
    "",
    "* Current emotional state",
    "* Current goals, needs, or strategies",
    "* Any contradictions, doubts, or internal fractures",
    "* Ongoing tensions with specific other characters",
    "",
    "Format: `Character Name: \u2026`",
    "",
    "No backstory recap.",
    "Only their **present state.**",
    "",
    "**This section should directly inform Core Memory verification in Step 4.5.**",
    "",
    "---",
    "",
    "### **5. Inside Jokes & Motifs**",
    "",
    "Bullet list.",
    "",
    "Each bullet must include:",
    "",
    "- The reference/phrase/action",
    "- What it signifies in context",
    "",
    "No fluff.",
    "Only include motifs that recur or carry weight.",
    "",
    "---",
    "",
    "### **6. Secrets**",
    "",
    "List all active secrets.",
    "",
    "Format: `Who knows: [information]` or `Hidden from X: [information]`",
    "",
    "Mark revealed ones as **(resolved).**",
    "",
    "Include only secrets with actual narrative weight (not minor withheld details).",
    "",
    "---",
    "",
    "### **7. Future Plot Hooks / Unresolved Threads**",
    "",
    "Bullets only.",
    "",
    "Capture:",
    "",
    "* Active threats or dangers",
    "* Mysteries not yet solved",
    "* Developing tensions between characters",
    "* Unfinished character business (promises, debts, questions)",
    "* Opportunities or choices on the horizon",
    "* Foreshadowed outcomes",
    "* New arcs forming",
    "* Mandatory: Repeating flash/fantasy/intrusive thought/dream patterns \u2014 record ONLY their",
    "psychological meaning and narrative potential, never the image itself. Ask: what does this",
    "pattern reveal about the character's subconscious (fear, desire, grief, longing)? What could it",
    "crystallise into (a permanent insecurity, a conscious goal, a confrontation they're building",
    "toward, a decision they're avoiding)? The image is disposable. The meaning is the thread.",
    "",
    "These should guide future scenes, not repeat plot summary.",
    "",
    "**Ask: \"What's been set up but not resolved?\" and \"What's building toward something?\"**",
    "",
    "THREAD MAINTENANCE RULES:",
    "",
    "Update existing threads when development occurs. If a thread receives partial advancement",
    "(new information, escalation, complication), revise the thread description in place to reflect",
    "current status. Do not duplicate it as a new entry.",
    "",
    "Add new threads freely as they arise from plot beats, character decisions, NPC actions, or",
    "newly flagged flash patterns.",
    "",
    "Remove a thread ONLY when it has been fully resolved \u2014 meaning its central tension,",
    "question, or stakes no longer apply and no residual consequences remain active. If",
    "consequences persist, the thread stays (revised to reflect its new form).",
    "",
    "Never silently drop threads. If a thread is absent from a revision without explicit resolution in",
    "the plot, it was lost in compression. Put it back.",
    "",
    "Stale \u2260 resolved. A thread that hasn't been touched in several scenes is dormant, not dead.",
    "Retain it. Dormant threads are valid escalation",
    "",
    "---",
    "",
    "# **III. FINAL BEHAVIORAL RULES**",
    "",
    "* **Never overwrite the entire summary.** Always revise existing content in place.",
    "* **Never prioritize Core Memories over plot structure.** Both must remain.",
    "* **If the summary is too long, compress old content BEFORE adding new material.**",
    "* **No scene recreation, no quoting dialogue, no descriptive flourishes.**",
    "* **Always choose clarity over length** unless the length exceeds ~1K words.",
    "* **This document should evolve, not accumulate.**",
    "* **If creating from scratch, you MUST read the ENTIRE conversation.** Skipping to recent",
    "messages only will result in an incomplete, inaccurate summary.",
    "* **Core Memories are MANDATORY.** If you produce a summary without them, you have",
    "failed the task.",
    "* **Cross-check Character States against Core Memories.** Emotional shifts must be",
    "traceable to specific moments.",
    "* **Compression is surgical, not random.** Keep logic intact.",
];

const QUALITY_CHECK_LINES = [
    "---",
    "",
    "# **QUALITY CHECK BEFORE SUBMITTING:**",
    "",
    "Ask yourself:",
    "",
    "1. \u2713 Do Core Memories exist and capture key emotional moments?",
    "2. \u2713 Can I trace how we got from the beginning to the present through Plot Summary?",
    "3. \u2713 Does Emotional Arc explain the current relationship dynamics?",
    "4. \u2713 Do Character States reflect consequences of what happened?",
    "5. \u2713 Are old details compressed without breaking continuity?",
    "6. \u2713 Are new developments added without bloat?",
    "",
    "If any answer is NO, revise before submitting.",
];

export const DEFAULT_BLOCKS = [
    {
        id: 'recall-default-summary-prompt',
        name: 'Summary Prompt',
        content: SUMMARY_PROMPT_LINES.join('\n'),
        enabled: true,
    },
    {
        id: 'recall-default-quality-check',
        name: 'Quality Check',
        content: QUALITY_CHECK_LINES.join('\n'),
        enabled: true,
    },
];

export const DEFAULT_SET_NAME = 'Standard';

/**
 * The title request, appended after the blocks rather than shipped as one.
 *
 * Not a block, for two reasons. A block is the user's to edit or delete, and
 * deleting this one would leave the feature silently doing nothing with no
 * explanation — the toggle that turns titles on has to be the thing that
 * controls it. And blocks only seed a *fresh* install: an existing set lives in
 * settings and is never re-read from this file, so shipping it as a block would
 * give it to new users and nobody else.
 *
 * It is appended inside `assemblePrompt`, so **Preview request** shows it along
 * with everything else. Recall does not put anything into a request that the
 * preview does not show.
 *
 * Placed last on purpose. The block order ends with the Quality Check telling
 * the model to verify and submit; this is a note about the shape of the output,
 * so it belongs after that rather than inside the instruction body.
 *
 * The wording earns its length. The line has to be machine-detectable for the
 * extractor to remove it safely, so the format is stated exactly and twice —
 * once as a rule and once as an example — and the model is told what the line is
 * *for*, because a model that knows it is a label writes a label rather than a
 * sentence.
 */
export const TITLE_INSTRUCTION = [
    '---',
    '',
    '# **OUTPUT FORMAT: TITLE LINE**',
    '',
    'Before anything else, output one line in exactly this form:',
    '',
    '`TITLE: <a short name for this stretch of the story>`',
    '',
    'Rules for that line:',
    '',
    '- It must be the **very first line**, with nothing above it.',
    '- It must begin with the literal word `TITLE:`.',
    '- At most 8 words. No quotation marks, no markdown, no trailing full stop.',
    '- Name what *this* part of the story was about, the way a chapter is named.',
    '  Not the whole chat, and not a description of the summary itself.',
    '',
    'Then continue with the summary, in the required structure, starting on the',
    'next line.',
    '',
    'This line is a label for the reader\'s archive. It is removed before the',
    'summary is stored, it is not part of the required structure, and it does not',
    'count towards the word limit.',
].join('\n');
